Re-implemented clustering of snapshots
mala-project/mala pull request #249
Opened 2022-02-02 16:53 UTC by RandomDefaultUser

Closes #246 .

2022-02-02 23:32 UTC, ellisja requested changes
Very nice. Just a few small typos that I found.

2022-02-03 08:13 UTC, RandomDefaultUser commented on mala/common/parameters.py
> +    numbers_of_cluster : int
Fixed in [0098144](https://github.com/mala-project/mala/pull/249/commits/0098144914ebd23b6979d060f9f2f8928eb0be41).

2022-02-03 08:13 UTC, RandomDefaultUser commented on mala/common/parameters.py
> +        self.sample_ration = 0.0
Fixed in [0098144](https://github.com/mala-project/mala/pull/249/commits/0098144914ebd23b6979d060f9f2f8928eb0be41).

2022-02-03 08:13 UTC, RandomDefaultUser commented on mala/common/parameters.py
> +    sample_ration : float
Fixed in [0098144](https://github.com/mala-project/mala/pull/249/commits/0098144914ebd23b6979d060f9f2f8928eb0be41).

2022-02-03 08:15 UTC, RandomDefaultUser commented
Thanks for the feedback @ellisja ! I fixed the typos. I also deleted the files in the ml-dft-sandia folder that this merge request incorporates into the mala core code. One final question - in the implementation of this PR, only the training data set is clustered, validation and test data set are never clustered. Is that alright?

2022-02-03 12:58 UTC, ellisja commented
> Thanks for the feedback @ellisja ! I fixed the typos. I also deleted the files in the ml-dft-sandia folder that this merge request incorporates into the mala core code. One final question - in the implementation of this PR, only the training data set is clustered, validation and test data set are never clustered. Is that alright?

Yes, that's right. The validation and test set are only used for forward inference calculations and would not benefit as much as the training set.

2022-02-03 14:07 UTC, ellisja approved these changes

2022-02-03 16:22 UTC, merged