Updating documentation
mala-project/mala pull request #391
Opened 2022-12-23 11:30 UTC by RandomDefaultUser

Added info about creating releases and adding dependencies.

2022-12-28 16:05 UTC, DanielKotik requested changes

2022-12-28 16:05 UTC, DanielKotik commented on docs/source/CONTRIBUTE.md
> +add them in the `Dockerfile` for the `conda` environment build.
```suggestion
Further, in order for them to be available during the CI tests, make sure to 
add _required_ dependencies to the appropriate environment files in folder `install/` and _extra_ requirements directly in the `Dockerfile` for the `conda` environment build.
```

2023-01-02 07:38 UTC, RandomDefaultUser commented on docs/source/CONTRIBUTE.md
> +5. Edit the release on GitHub, by e.g. adding release notes/change log
Sounds good, thank you!

2023-01-02 10:05 UTC, DanielKotik approved these changes

2023-01-02 10:06 UTC, merged