Add warning for lammps pre-processing
mala-project/mala pull request #503
Opened 2024-02-13 09:10 UTC by timcallow

Warning for users when pre-processing SNAP with lammps.  This is a temporary workaround for issue #502

2024-02-19 13:51 UTC, RandomDefaultUser requested changes
Thanks for the PR @timcallow, I agree that for now (until we have fixed the underlying issue) a warning like this is the best way to proceed. MALA has a parallel warning function that I would suggest we use instead of the printout function.

2024-02-19 13:51 UTC, RandomDefaultUser commented on mala/descriptors/descriptor.py
> +in the same directory at the same time. Data may be over-written.")
```suggestion
parallel_warn("Do not initialize more than one pre-processing calculation\
in the same directory at the same time. Data may be over-written.")
```

2024-02-20 07:55 UTC, timcallow commented
Thanks for the suggestion, I didn't notice that function - I've committed your change

2024-02-20 10:55 UTC, RandomDefaultUser approved these changes
Thanks, looks good to me now! :)

2024-02-20 10:55 UTC, merged